version: "3"
services:
  app:
    container_name: node-app
    build: .
    volumes:
      - ./server:/usr/src/app/server
    command: npm start
    restart: always
    ports:
      - "8080:3000"
    external_links:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

volumes:
  db-config:
  db-data:
